<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>GitDelta.Diff</RootNamespace>
    <AssemblyName>GitDelta.Diff</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GitDelta.Core\GitDelta.Core.csproj" />
    <PackageReference Include="TextMateSharp" />
    <PackageReference Include="TextMateSharp.Grammars" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="MinVer" PrivateAssets="all" />
  </ItemGroup>
</Project>
