<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>GitDelta.Persistence</RootNamespace>
    <AssemblyName>GitDelta.Persistence</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GitDelta.Core\GitDelta.Core.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="MinVer" PrivateAssets="all" />
  </ItemGroup>
</Project>
