<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CodeReviewr.TestSupport</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\CodeReviewr.Core\CodeReviewr.Core.csproj" />
    <ProjectReference Include="..\..\src\CodeReviewr.Git\CodeReviewr.Git.csproj" />
  </ItemGroup>
</Project>
