<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>GitDelta.GitHub</RootNamespace>
    <AssemblyName>GitDelta.GitHub</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="GitDelta.GitHub.Tests" />
    <InternalsVisibleTo Include="GitDelta.Review" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GitDelta.Core\GitDelta.Core.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="MinVer" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Queries\**\*.graphql" />
  </ItemGroup>
</Project>
