<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CodeReviewr.Diff</RootNamespace>
    <AssemblyName>CodeReviewr.Diff</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CodeReviewr.Core\CodeReviewr.Core.csproj" />
    <PackageReference Include="TextMateSharp" />
    <PackageReference Include="TextMateSharp.Grammars" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="MinVer" PrivateAssets="all" />
  </ItemGroup>
</Project>
