<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CodeReviewr.Git</RootNamespace>
    <AssemblyName>CodeReviewr.Git</AssemblyName>
  </PropertyGroup>
<ItemGroup>
    <InternalsVisibleTo Include="CodeReviewr.Git.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CodeReviewr.Core\CodeReviewr.Core.csproj" />
    <PackageReference Include="CliWrap" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="MinVer" PrivateAssets="all" />
  </ItemGroup>
</Project>
