<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CodeReviewr.GitHub</RootNamespace>
    <AssemblyName>CodeReviewr.GitHub</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="CodeReviewr.GitHub.Tests" />
    <InternalsVisibleTo Include="CodeReviewr.Review" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CodeReviewr.Core\CodeReviewr.Core.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="MinVer" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Queries\**\*.graphql" />
  </ItemGroup>
</Project>
