created: 2026-08-06T18:00:17.014Z
updated: 2026-08-06T18:00:17.015Z
update_count: 1
last_field: description
kind: nested-class
title: paint-cache
children: []
parentPath:
  - app-shell
  - diff-viewer
